# Generated by Django 4.0.1 on 2022-01-27 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Department_NAME', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('Employer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Employer_NAME', models.CharField(max_length=100)),
                ('Employer_GENDER', models.CharField(max_length=30)),
                ('Employer_age', models.IntegerField(default=0)),
                ('Date_of_Join', models.DateField(null=True)),
                ('Photo_Image', models.ImageField(blank=True, null=True, upload_to='emp/images/%Y/%m/%d')),
                ('upload_at', models.DateTimeField(auto_now=True, null=True)),
                ('Department_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department')),
            ],
        ),
    ]
